In [46]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
import re
from collections import Counter
import random
import ast

# Робота з базою данних рецептів

In [47]:
recipes_base = pd.read_csv("data/recipes.csv")

In [48]:
recipes_df = pd.read_csv("data/recipes.csv")

In [49]:
type(recipes_df["RecipeIngredientParts"].loc[344])

str

In [50]:
recipes_df.head()

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,RecipeCategory,Keywords,RecipeIngredientQuantities,RecipeIngredientParts,AggregatedRating,ReviewCount,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",Frozen Desserts,"c(""Dessert"", ""Low Protein"", ""Low Cholesterol"",...","c(""4"", ""1/4"", ""1"", ""1"")","c(""blueberries"", ""granulated sugar"", ""vanilla ...",4.5,4.0,170.9,2.5,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",Chicken Breast,"c(""Chicken Thigh & Leg"", ""Chicken"", ""Poultry"",...","c(""1"", ""4"", ""2"", ""2"", ""8"", ""1/4"", ""8"", ""1/2"", ...","c(""saffron"", ""milk"", ""hot green chili peppers""...",3.0,1.0,1110.7,58.8,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",Beverages,"c(""Low Protein"", ""Low Cholesterol"", ""Healthy"",...","c(""1 1/2"", ""1"", NA, ""1 1/2"", NA, ""3/4"")","c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...",4.5,10.0,311.1,0.2,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,"c(""https://img.sndimg.com/food/image/upload/w_...",Soy/Tofu,"c(""Beans"", ""Vegetable"", ""Low Cholesterol"", ""We...","c(""12"", ""1"", ""2"", ""1"", ""10"", ""1"", ""3"", ""2"", ""2...","c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...",4.5,2.0,536.1,24.0,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,42,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,"""https://img.sndimg.com/food/image/upload/w_55...",Vegetable,"c(""Low Protein"", ""Vegan"", ""Low Cholesterol"", ""...","c(""46"", ""4"", ""1"", ""2"", ""1"")","c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...",4.5,11.0,103.6,0.4,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil..."

In [51]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522517 entries, 0 to 522516
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RecipeId                    522517 non-null  int64
 1   Name                        522517 non-null  object
 2   AuthorId                    522517 non-null  int64
 3   AuthorName                  522517 non-null  object
 4   CookTime                    439972 non-null  object
 5   PrepTime                    522517 non-null  object
 6   TotalTime                   522517 non-null  object
 7   DatePublished               522517 non-null  object
 8   Description                 522512 non-null  object
 9   Images                      522516 non-null  object
 10  RecipeCategory              521766 non-null  object
 11  Keywords                    505280 non-null  object
 12  RecipeIngredientQuantities  522514 non-null  object
 13  RecipeIngredientParts       522517 non-null  object
 14  AggregatedRating            269294 non-null  float64
 15  ReviewCount                 275028 non-null  float64
 16  Calories                    522517 non-null  float64
 17  FatContent                  522517 non-null  float64
 18  SaturatedFatContent         522517 non-null  float64
 19  CholesterolContent          522517 non-null  float64
 20  SodiumContent               522517 non-null  float64
 21  CarbohydrateContent         522517 non-null  float64
 22  FiberContent                522517 non-null  float64
 23  SugarContent                522517 non-null  float64
 24  ProteinContent              522517 non-null  float64
 25  RecipeServings              339606 non-null  float64
 26  RecipeYield                 174446 non-null  object
 27  RecipeInstructions          522517 non-null  object
dtypes: float64(12), int64(2), object(14)
memory usage: 111.6+ MB

In [52]:
# def extract_ingredients(r_string):
#     # Извлекаем все строки в кавычках
#     return re.findall(r'"(.*?)"', r_string)

# # Преобразуем все строки в списки ингредиентов
# recipes_df['IngredientList'] = recipes_df['RecipeIngredientParts'].apply(extract_ingredients)

# # Объединяем все списки в один и приводим к нижнему регистру
# all_ingredients = [ingredient.strip().lower() for sublist in recipes_df['IngredientList'] for ingredient in sublist]

# # Считаем частоты
# ingredient_counts = Counter(all_ingredients)

# # В датафрейм
# ingredient_df = pd.DataFrame(ingredient_counts.items(), columns=["Ingredient", "Count"]).sort_values(by="Count", ascending=False)

# # Топ-20
# print(ingredient_df.head)
# print(len(ingredient_df))

In [53]:
list_to_drop = ['RecipeId', 'AuthorName','Images','RecipeYield', 'RecipeServings', 'ReviewCount', 'CookTime', 'PrepTime', 'DatePublished', 'RecipeCategory', 'Keywords', 'RecipeIngredientQuantities', 'AuthorId', 'Description']

In [54]:
recipes_df.drop(list_to_drop, axis=1, inplace=True)

In [55]:
recipes_df.replace('character(0)', None, inplace=True)

In [56]:
recipes_df = recipes_df.dropna(subset=['RecipeIngredientParts'])

In [57]:
recipes_df = recipes_df.dropna(subset=['RecipeInstructions'])

-1 буде значити що оцінки немає для стовпця AggregatedRating

In [58]:
recipes_df['AggregatedRating'] = recipes_df['AggregatedRating'].fillna(-1)

In [59]:
recipes_df[recipes_df.isna().any(axis=1)]

Empty DataFrame
Columns: [Name, TotalTime, RecipeIngredientParts, AggregatedRating, Calories, FatContent, SaturatedFatContent, CholesterolContent, SodiumContent, CarbohydrateContent, FiberContent, SugarContent, ProteinContent, RecipeInstructions]
Index: []

In [60]:
recipes_df[recipes_df['RecipeInstructions'].isna()]

Empty DataFrame
Columns: [Name, TotalTime, RecipeIngredientParts, AggregatedRating, Calories, FatContent, SaturatedFatContent, CholesterolContent, SodiumContent, CarbohydrateContent, FiberContent, SugarContent, ProteinContent, RecipeInstructions]
Index: []

In [61]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 520297 entries, 0 to 522516
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Name                   520297 non-null  object
 1   TotalTime              520297 non-null  object
 2   RecipeIngredientParts  520297 non-null  object
 3   AggregatedRating       520297 non-null  float64
 4   Calories               520297 non-null  float64
 5   FatContent             520297 non-null  float64
 6   SaturatedFatContent    520297 non-null  float64
 7   CholesterolContent     520297 non-null  float64
 8   SodiumContent          520297 non-null  float64
 9   CarbohydrateContent    520297 non-null  float64
 10  FiberContent           520297 non-null  float64
 11  SugarContent           520297 non-null  float64
 12  ProteinContent         520297 non-null  float64
 13  RecipeInstructions     520297 non-null  object
dtypes: float64(10), object(4)
memory usage: 59.5+ MB

In [62]:
def parse_iso_duration(duration):
    if not isinstance(duration, str):
        return 0
    hours = re.search(r'(\d+)H', duration)
    minutes = re.search(r'(\d+)M', duration)
    total_minutes = 0
    if hours:
        total_minutes += int(hours.group(1)) * 60
    if minutes:
        total_minutes += int(minutes.group(1))
    return total_minutes

recipes_df['TotalTimeMinutes'] = recipes_df['TotalTime'].apply(parse_iso_duration)
recipes_df.drop('TotalTime', axis=1, inplace=True)

In [63]:
def parse_object(s):
    if not isinstance(s, str):
        print(s, type(s))
        return []
    s = s.strip()  # Убираем пробелы по краям
    
    if s.startswith("c(") and s.endswith(")"):
        # Удаляем c( и )
        s_inner = s[2:-1]
        # Извлекаем все элементы в двойных кавычках
        items = re.findall(r'"(.*?)"', s_inner)
        return items
    
    # Обработка одиночного элемента в кавычках, например '"powdered sugar"'
    m = re.fullmatch(r'"(.*?)"', s)
    if m:
        # print(m.group(1))
        return [m.group(1)]
    return []
recipes_df['RecipeIngredientParts'] = recipes_df['RecipeIngredientParts'].apply(parse_object)

In [64]:
recipes_df['RecipeInstructions'] = recipes_df['RecipeInstructions'].apply(parse_object)

In [65]:
# recipes_df['Images'] = recipes_df['Images'].apply(parse_object)

In [66]:
recipes_df['RecipeIngredientParts'] = recipes_df['RecipeIngredientParts'].apply(
    lambda lst: [s.lower() for s in lst] if isinstance(lst, list) else lst
)

In [67]:
recipes_df

,Name,RecipeIngredientParts,AggregatedRating,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeInstructions,TotalTimeMinutes
0,Low-Fat Berry Blue Frozen Dessert,"[blueberries, granulated sugar, vanilla yogurt...",4.5,170.9,2.5,1.3,8.0,29.8,37.1,3.6,30.2,3.2,"[Toss 2 cups berries with sugar., Let stand fo...",1485
1,Biryani,"[saffron, milk, hot green chili peppers, onion...",3.0,1110.7,58.8,16.6,372.8,368.4,84.4,9.0,20.4,63.4,[Soak saffron in warm milk for 5 minutes and p...,265
2,Best Lemonade,"[sugar, lemons, rind of, lemon, zest of, fresh...",4.5,311.1,0.2,0.0,0.0,1.8,81.5,0.4,77.2,0.3,"[Into a 1 quart Jar with tight fitting lid, pu...",35
3,Carina's Tofu-Vegetable Kebabs,"[extra firm tofu, eggplant, zucchini, mushroom...",4.5,536.1,24.0,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,"[Drain the tofu, carefully squeezing out exces...",1460
4,Cabbage Soup,"[plain tomato juice, cabbage, onion, carrots, ...",4.5,103.6,0.4,0.1,0.0,959.3,25.1,4.8,17.7,4.3,"[Mix everything together and bring to a boil.,...",50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522512,Meg's Fresh Ginger Gingerbread,"[fresh ginger, unsalted butter, dark brown sug...",-1.0,316.6,12.5,7.6,54.4,278.2,48.5,0.8,22.8,3.9,[Preheat oven to 350&deg;F Grease an 8x8 cake ...,95
522513,Roast Prime Rib au Poivre with Mixed Peppercorns,"[dijon mustard, garlic, peppercorns, shallot, ...",-1.0,2063.4,172.4,71.4,433.8,766.3,3.2,0.7,0.1,117.0,[Position rack in center of oven and preheat t...,210
522514,Kirshwasser Ice Cream,"[half-and-half, heavy cream, brandy, sugar]",-1.0,1271.3,117.2,72.6,470.9,192.5,33.9,0.0,17.3,12.8,[heat half and half and heavy cream to a simme...,240
522515,Quick & Easy Asian Cucumber Salmon Rolls,"[wasabi paste, dill, english cucumber, smoked ...",-1.0,16.1,0.6,0.1,2.9,100.5,0.3,0.0,0.1,2.4,"[In a small bowl, combine mayo and wasabi past...",15
522516,Spicy Baked Scotch Eggs,"[hard-boiled eggs, breakfast sausage, panko br...",-1.0,1093.3,71.2,22.2,1769.7,1318.6,29.7,1.3,6.7,76.4,"[Mix sausage, panko, egg yolk and Wocestershir...",40

In [68]:
recipes_df['RecipeIngredientParts'] = recipes_df['RecipeIngredientParts'].apply(lambda x: np.nan if x == [] else x)

In [69]:
recipes_df[recipes_df['RecipeIngredientParts'].isna()]

Empty DataFrame
Columns: [Name, RecipeIngredientParts, AggregatedRating, Calories, FatContent, SaturatedFatContent, CholesterolContent, SodiumContent, CarbohydrateContent, FiberContent, SugarContent, ProteinContent, RecipeInstructions, TotalTimeMinutes]
Index: []

In [70]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 520297 entries, 0 to 522516
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Name                   520297 non-null  object
 1   RecipeIngredientParts  520297 non-null  object
 2   AggregatedRating       520297 non-null  float64
 3   Calories               520297 non-null  float64
 4   FatContent             520297 non-null  float64
 5   SaturatedFatContent    520297 non-null  float64
 6   CholesterolContent     520297 non-null  float64
 7   SodiumContent          520297 non-null  float64
 8   CarbohydrateContent    520297 non-null  float64
 9   FiberContent           520297 non-null  float64
 10  SugarContent           520297 non-null  float64
 11  ProteinContent         520297 non-null  float64
 12  RecipeInstructions     520297 non-null  object
 13  TotalTimeMinutes       520297 non-null  int64
dtypes: float64(10), int64(1), object(3)
memory usage: 59.5+ MB

In [71]:
# recipes_df['Name'] = recipes_df['Name'].astype('string')

In [72]:
# recipes_df['AuthorName'] = recipes_df['AuthorName'].astype('string')

In [73]:
recipes_df.to_csv('data/recipes_cleaned.csv', index=False)

#